### ISSUE TITLE
UE 5.3 - FRayTracingInstance - Will not build

### ISSUE THREAD

**Issue by Darkstar130** [iTwin/unreal-engine-3dft-plugin#20]
LNK2019	unresolved external symbol "public: void __cdecl FRayTracingInstance::BuildInstanceMaskAndFlags(enum ERHIFeatureLevel::Type)" (?BuildInstanceMaskAndFlags@FRayTracingInstance@@QEAAXW4Type@ERHIFeatureLevel@@@Z) referenced in function "public: virtual void __cdecl FProceduralMeshSceneProxy::GetDynamicRayTracingInstances(struct FRayTracingMaterialGatheringContext &,class TArray<struct FRayTracingInstance,class TSizedDefaultAllocator<32> > &)" (?GetDynamicRayTracingInstances@FProceduralMeshSceneProxy@@UEAAXAEAUFRayTracingMaterialGatheringContext@@AEAV?$TArray@UFRayTracingInstance@@V?$TSizedDefaultAllocator@$0CA@@@@@@Z)	iTwinExample	C:\Users\***\***\unreal-engine-3dft-plugin-main\unreal-engine-3dft-plugin-main\Intermediate\ProjectFiles\Module.iTwin.cpp.obj	

Looks like it was changed in 5.2 https://docs.unrealengine.com/5.2/en-US/unreal-engine-5.2-release-notes/ But it will not build on 5.3

**Comment by danieliborra** [comment]
Hello,

thanks you for your feedback.
We wrote this plugin for 5.0.3 and we don't have short-term plans to update to 5.3.
Since it is open-source, please, let me know if you have plans to update it to 5.3 so we could update it in this repo too.
